apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: alpino
spec:
  template:
    metadata:
      labels:
        app: alpino
    spec:
      containers:
        - name: alpine
          image: alpine:3.8
          command: ["top"]
