apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: my-redis
    spec:
      containers:
      - name: my-redis
        image: redis:5
        env:
          - name: CRED
            value: "{hashi.secret/DB_CONN}"
