apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: two-containers
  namespace: apps
spec:
  template:
    metadata:
      labels:
        run: two-containers
    spec:
      containers:
      - name: nginx
        image: nginx:1.15
        ports:
        - containerPort: 80
      - name: alpine
        image: alpine:3.7
        command: ["watch", "wget", "-qO-", "localhost"]
